//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomersInfo()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int CustomersInfo_Id { get; set; }
        public Nullable<int> Visits_Id { get; set; }
        public string CustomersInfo_Allergy { get; set; }
        public int Diagnosis_Id { get; set; }
        public string Customers_Drugs { get; set; }
        public int Researches_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Researches Researches { get; set; }
        public virtual Visits Visits { get; set; }
    }
}
