//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DentalFormula
    {
        public int DentalFormula_Id { get; set; }
        public string DentalFormula_Formula { get; set; }
        public string DentalFormula_Description { get; set; }
        public Nullable<int> Client_Id_FK { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
