//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        public Diagnosis()
        {
            this.DiagnosisHistory = new HashSet<DiagnosisHistory>();
        }
    
        public int Diagnosis_Id { get; set; }
        public string Diagnosis_Name { get; set; }
        public string Diagnosis_Description { get; set; }
    
        public virtual ICollection<DiagnosisHistory> DiagnosisHistory { get; set; }
    }
}
