//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        public int Diagnosis_Id { get; set; }
        public string Diagnosis_Name { get; set; }
    
        public virtual CustomersInfo CustomersInfo { get; set; }
    }
}
