//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosisHistory
    {
        public int DiagnosisHistory_Id { get; set; }
        public int Diagnosis_Id_FK { get; set; }
        public int Clients_Id_FK { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Diagnosis Diagnosis { get; set; }
    }
}
