//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugs
    {
        public Drugs()
        {
            this.DrugsInfo = new HashSet<DrugsInfo>();
        }
    
        public int Drugs_Id { get; set; }
        public string Drugs_Name { get; set; }
        public string Drugs_Description { get; set; }
    
        public virtual ICollection<DrugsInfo> DrugsInfo { get; set; }
    }
}
