//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentistryEntities : DbContext
    {
        public DentistryEntities()
            : base("name=DentistryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergy> Allergy { get; set; }
        public virtual DbSet<AllergyInfo> AllergyInfo { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<DentalFormula> DentalFormula { get; set; }
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<DiagnosisHistory> DiagnosisHistory { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<DrugsInfo> DrugsInfo { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesHistory> ServicesHistory { get; set; }
        public virtual DbSet<Studies> Studies { get; set; }
        public virtual DbSet<Visits> Visits { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
