//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentistryEntities : DbContext
    {
        public DentistryEntities()
            : base("name=DentistryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Allergy> Allergy { get; set; }
        public DbSet<AllergyInfo> AllergyInfo { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<DentalFormula> DentalFormula { get; set; }
        public DbSet<Diagnosis> Diagnosis { get; set; }
        public DbSet<DiagnosisHistory> DiagnosisHistory { get; set; }
        public DbSet<Drugs> Drugs { get; set; }
        public DbSet<DrugsInfo> DrugsInfo { get; set; }
        public DbSet<Personal> Personal { get; set; }
        public DbSet<PhotoPersonal> PhotoPersonal { get; set; }
        public DbSet<Registration> Registration { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<ServicesHistory> ServicesHistory { get; set; }
        public DbSet<Studies> Studies { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Visits> Visits { get; set; }
    }
}
