//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoPersonal
    {
        public int PhotoPersonal_Id { get; set; }
        public byte[] PhotoPersonal_Image { get; set; }
        public int Personal_Id_FK { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
