//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public Services()
        {
            this.ServicesHistory = new HashSet<ServicesHistory>();
        }
    
        public int Services_Id { get; set; }
        public string Services_Code { get; set; }
        public string Services_Name { get; set; }
        public string Services_Count { get; set; }
    
        public virtual ICollection<ServicesHistory> ServicesHistory { get; set; }
    }
}
