//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studies
    {
        public int Studies_Id { get; set; }
        public string Studies_Name { get; set; }
        public string Studies_Description { get; set; }
        public byte[] Studies_Image { get; set; }
        public int Clients_Id_FK { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
