//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistryWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visits()
        {
            this.Registration = new HashSet<Registration>();
        }
    
        public int Visits_Id { get; set; }
        public System.DateTime Visits_Date { get; set; }
        public string Visits_TransferredDiseases { get; set; }
        public string Visits_Complaints { get; set; }
        public string Visits_RealDisease { get; set; }
        public string Visits_MucousMembrane { get; set; }
        public string Visits_Rentgen { get; set; }
        public string Visits_Sovet { get; set; }
        public string Visits_Result { get; set; }
        public string Visits_Diagnosis { get; set; }
        public int Clients_Id_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registration { get; set; }
    }
}
